# Generated by Django 3.1.4 on 2021-02-01 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210201_2330'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogauthor',
            old_name='name',
            new_name='user',
        ),
    ]
