# Generated by Django 3.1.4 on 2021-02-02 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210201_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcomment',
            name='post_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
