# Generated by Django 3.1.4 on 2021-02-02 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210202_1339'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogcomment',
            options={'ordering': ['post_date']},
        ),
        migrations.AlterField(
            model_name='blog',
            name='description',
            field=models.TextField(help_text='Enter a description about blog', max_length=1000),
        ),
        migrations.AlterField(
            model_name='blog',
            name='name',
            field=models.CharField(help_text='Enter the blog name', max_length=100),
        ),
        migrations.AlterField(
            model_name='blogauthor',
            name='bio',
            field=models.CharField(help_text='Enter a bio about Blog Author', max_length=100),
        ),
        migrations.AlterField(
            model_name='blogcomment',
            name='description',
            field=models.TextField(help_text='Enter comment about blog here', max_length=1000),
        ),
    ]
